# 异常

## 超类： Throable接口
Throwable 包含了其线程创建时线程执行堆栈的快照，printStackTrace() 打印堆栈
 - Error
 - Exception

## Error
 - OOM
 - SO
LinkageError

系统级别,JVM会终止进程,不是本应用的处理级别
不要继承实现！！

## Exception
### 受检异常: 可以try catch

写代码时就**可以预测**的。
要提前处理,否则编译无法通过。

**除了RuntimeException及其子类**以外，
其他的Exception类及其子类都属于这种异常.

 - try-catch语句进行捕获，
 - throws子句抛出，

### throw 和 throws
方法体内,抛出 throw xxx
方法签名处,声明可能抛出throws


### 非受检异常
#### RuntimeException 及其子类
编译不检查， 运行时可能抛出
但写的时候，自己要发现。

Arithmetic Exception： 除0，会导致崩溃
NullPointer

## finally
在不终止 JVM 的情况下, 执行了try, finally 中的代码一定会执行
而且 finally 块里 return 语句会把 try 块或者 catch 块里的 return 语句效果给覆盖掉且吞掉了异常。

[常见面试题](https://www.cnblogs.com/ljangle/p/10681782.html)

### try with resource
finally & close()
close()本身也可能异常
java7 ，需要**自动释放**的资源可以实现了 AutoCloseable 接口的类
避免多层trycatch


## 标准异常
|                                 |                                           |
|---------------------------------|-------------------------------------------|
| IllegalArgumentException        | 参数的值不合适                            |
| IllegalStateException           | 参数的状态不合适                          |
| NullPointerException            | 在null被禁止的情况下参数值为null          |
| IndexOutOfBoundsException       | 下标越界                                  |
| ConcurrentModificationException | 在禁止并发修改的情况下，对象检测到并发修改 |
| UnsupportedOperationException   | 对象不支持客户请求的方法                  |


## 禁忌
不要忽略异常，无日志
不要catch 后抛, 重复日志
不要丢原始异常, e 作为参数继续传递，避免堆栈丢失
不要捕捉Throwable
不要用异常做控制流
不要finally return ，覆盖 try 中返回点

## 底层实现
```java
//javap -c Main
 public static void simpleTryCatch();
    Code:
       0: invokestatic  #3                  // Method testNPE:()V
       3: goto          11
       6: astore_0
       7: aload_0
       8: invokevirtual #5                  // Method java/lang/Exception.printStackTrace:()V
      11: return
    Exception table:
       from    to  target type
           0     3     6   Class java/lang/Exception
// 异常表，记录trycatch代码位置
// 逐条找合适的处理
// 再者，弹栈帧
```